server {
    listen 80;
    server_name localhost;
    
    index index.php index.html;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    # Route Ordering Service
    location ^~ /api/orders {
        alias /var/www/html/ordering-service/public;
        try_files $uri $uri/ @ordering;
        
        location ~ \.php$ {
            fastcgi_pass ordering-app:9000;
            fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
            include fastcgi_params;
        }
    }

    location @ordering {
        rewrite /api/orders/(.*)$ /api/orders/index.php?/$1 last;
    }

    # Route Notification/Search Service
    location ^~ /api/search {
        alias /var/www/html/notification-service/public;
        try_files $uri $uri/ @notification;
        
        location ~ \.php$ {
            fastcgi_pass notification-app:9000;
            fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
            include fastcgi_params;
        }
    }

    location @notification {
        rewrite /api/search/(.*)$ /api/search/index.php?/$1 last;
    }
}